"""added_meeting_table

Revision ID: 7cc9f1bb44fd
Revises: b7c9a2893122
Create Date: 2021-10-31 01:21:54.403086

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7cc9f1bb44fd'
down_revision = 'b7c9a2893122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('type_of_meeting', sa.Enum('personal', 'group', name='meetingtypeenum'), nullable=False),
    sa.Column('status', sa.Enum('created', 'approved', 'rejected', 'under_consideration', name='meetingstatusenum'), nullable=False),
    sa.Column('planned_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_community_id'), 'meetings', ['community_id'], unique=False)
    op.create_index(op.f('ix_meetings_creator_id'), 'meetings', ['creator_id'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_index(op.f('ix_meetings_type_of_meeting'), 'meetings', ['type_of_meeting'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_type_of_meeting'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_creator_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_community_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
