"""added community table

Revision ID: b7c9a2893122
Revises: a93fd5540200
Create Date: 2021-10-26 00:32:43.858265

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b7c9a2893122'
down_revision = 'a93fd5540200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('participants_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communities_creator_id'), 'communities', ['creator_id'], unique=False)
    op.add_column('users', sa.Column('participates_in', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'participates_in')
    op.drop_index(op.f('ix_communities_creator_id'), table_name='communities')
    op.drop_table('communities')
    # ### end Alembic commands ###
